### ISSUE TITLE
Hey, do you know tRPC ？

### ISSUE THREAD

**Issue by cerjs** [unnoq/orpc#45]

**Comment by unnoq** [comment]
I've used tRPC extensively in the past, but it doesn't meet the efficiency requirements for my current use case.

**Comment by CarlosZiegler** [comment]
What is the diff betwwen both ? SOme benchmarks ? What is the proposal that tRPC does not cover?

Just curious :)

**Comment by unnoq** [comment]
The main purpose of oRPC is to serve as an alternative to TS-REST, not tRPC. Additionally, as I mentioned earlier, I’ve used tRPC in the past but migrated to TS-REST when my use case evolved.
