### ISSUE TITLE
Integration with Pinia Colada

### ISSUE THREAD

**Issue by tlebeitsuk** [unnoq/orpc#59]
Thanks for an very interesting project! I'm going to try to use it in my next Vue.js project. I'm also going to use [Pinia Colada](https://pinia-colada.esm.dev/) and wanted to ask if you would consider to make an oRPC integration for it. Pinia Colada shares similarities with TanStack Query and has adapted some of its APIs, so maybe the integration could be made without too much work?

Keep up the good work!

**Comment by unnoq** [comment]
Pinia seems popular and preferred over TanStack Query in the Vue community. Am I correct?

**Comment by unnoq** [comment]
I just look at Pinia Colada, it's simpler and more friendly with vue than tanstack-query, so Which package name is more suitable `@orpc/vue-colada` vs `@orpc/vue-pinia` I prefer pinia than

**Comment by tlebeitsuk** [comment]
What about @orpc/pinia-colada? You could also add vue if you think it makes more sense. I think it's beneficial to use the whole name so it's easier make the connection, also easier to find it here on GitHub and Google.

**Comment by unnoq** [comment]
> What about @orpc/pinia-colada? You could also add vue if you think it makes more sense. I think it's beneficial to use the whole name so it's easier make the connection, also easier to find it here on GitHub and Google.

Hope I can release it before new year!

**Comment by unnoq** [comment]
The `key` part of pinia-coladais not smart as tanstack query key, so we need to wait until the `key` part is smarter. @tlebeitsuk

**Comment by unnoq** [comment]
Please follow it

https://github.com/posva/pinia-colada/issues/149

**Comment by unnoq** [comment]
`@orpc/vue-colada` now available. @tlebeitsuk 

Wait https://github.com/unnoq/orpc/pull/65 for official announce

**Comment by tlebeitsuk** [comment]
Awesome! Thanks for taking the time!
